name: cd
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      REGION: us-central1
      PROJECT_ID: test1-479900
      REPOSITORY: notely-ar-repo
      IMAGE: notely
      TAG: latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.1"

    - name: Build Application
      run: ./scripts/buildprod.sh

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v3.0.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use gcloud credentials
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}
